FROM agrigorev/zoomcamp-model:mlops-2024-3.10.13-slim

WORKDIR /app

COPY [ "Pipfile", "Pipfile.lock", "homework.py", "./"]

RUN pip install -U pip
RUN pip install pipenv
RUN pipenv install --system --deploy

ENTRYPOINT [ "python", "homework.py", "2023", "5" ]